baseURL = "http://33eyes.github.io"
languageCode = "en-us"
title = "Arina Igumenshcheva"
theme = "tale"

[Author]
    name = "Arina Igumenshcheva"

[params]
    custom_css = ["css/custom.css"]

[taxonomies]
    tag = "tags"
    category = "categories"
